//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sklep.Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class CartItem
    {
        public CartItem()
        {
            this.Items = new HashSet<Item>();
        }
    
        public int CartItemID { get; set; }
        public int Quanity { get; set; }
        public decimal Prize { get; set; }
        public Nullable<int> CartID { get; set; }
    
        public virtual Cart Cart { get; set; }
        public virtual ICollection<Item> Items { get; set; }
    }
}
