//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sklep.Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        public Item()
        {
            this.CartItems = new HashSet<CartItem>();
        }
    
        public int ItemID { get; set; }
        public string Name { get; set; }
        public string Category { get; set; }
        public decimal Prize { get; set; }
        public string ImageUrl { get; set; }
        public int Quanity { get; set; }
    
        public virtual ICollection<CartItem> CartItems { get; set; }
    }
}
